### ISSUE TITLE
HTML tags not rendered

### ISSUE THREAD

**Issue by alex-dearden** [YarnSpinnerTool/YarnSpinner-Godot#24]
In the YarnSpinner docs, it states that you can render HTML tags by using Unity's TextMesh Pro so things like this would work from YarnSpinner:

> I want this <b>bold</b>

In Godot, this doesn't work, the tags get written tot he dialog. 

Godot supports BBCode style tags: [b]

Just wondering if it would be a good idea to parse the YarnSpinner text and replace <tag> with [tag] to keep consistency with the Unity platform and the YarnSpinner docs.

**Comment by dogboydog** [comment]
I would say as much as I've tried to make this as similar as possible to the Unity plugin, doc that relates to Unity specific features like TextMeshPro may not apply when the Godot equivalent (or closest thing to it) differs in convention or implementation details. 

Using the square brackets in yarn scripts directly would conflict with the YarnSpinner Markup feature https://docs.yarnspinner.dev/getting-started/writing-in-yarn/markup . In my game using YarnSpinner-Godot I use line markup  like [important] the text[/] and then fill in BbCode tags  based on the parsed markup details that the views receive. 

I'm not sure whether this plugin should try to automatically convert  < to [ for use in BBCode for example because that would then prevent anyone from using those characters in their dialogue, whereas that replacement could be built into a custom view with minimal code by the plugin user. 

Maybe the example views provided could have a boolean setting on them that would enable this behavior

**Comment by alex-dearden** [comment]
> Maybe the example views provided could have a boolean setting on them that would enable this behavior

Ooh that would be lovely. 

I was also thinking maybe we could include a parser helper file that does the conversion for you and your run it only once. But I like the boolean option much better :)

Also, would be great to update the YarnSpinner docs to mention this and other differences when using Godot. I'm happy to help with that in any way I can.

**Comment by alex-dearden** [comment]
Also, I didn't realise they would conflict with YarnSpinner's native markup. So even if we wanted to use BBCode directly in our scripts it wouldn't work. There would be more work to be done to make them work. 

This is something that should really be in the docs, along with an example on how to overcome it. WDYT?

Being fairly new to both Godot and YarnSpinner, I have no idea how to fix this but would be very happy to write a tutorial if you can provide me some examples.

**Comment by dogboydog** [comment]
> I was also thinking maybe we could include a parser helper file that does the conversion for you and your run it only once. But I like the boolean option much better :)

I don't know if that way would work unless you stored those replaced versions of the lines on disk somewhere. If you did it in-place on the .yarn files you would hit the issue where it would be interpreted as YarnSpinner markup  and not work as BBCode.   

YarnSpinner markup itself is one way to achieve this kind of feature though, because as I mentioned above, you can use markup in your .yarn files and then in your custom views, you can interpret this markup to style/animate/etc. your text - this is mentioned in the Markup article on the YarnSpinner docs site as well. 

I can add notes to the docs in this repo when I do a PR. For the time being I don't know all the plans of the full YarnSpinner doc site with regard to the Godot integration. They may want to wait until the functionality here becomes more settled.  When it comes to cases like TextMeshPro which is Unity only, assume it won't be 1:1 with Godot when referencing the docs. In this scenario YarnSpinner-Unity just doesn't care about  HTML tags and those happen to be able to pass through to TextMeshPro cleanly. 

My plan is to add a checkbox to the example LineView.cs that will automatically replace < and > with [ and ] at runtime if enabled, and that will let you write BBCode tags in HTML style. I think it will be off by default to not cause people to be confused why  < or > characters are not showing up in their dialogue at runtime.  I'll make a PR when I have a version working, and probably update one of the samples to demonstrate it

**Comment by alex-dearden** [comment]
Sounds good. Thanks again!

**Comment by dogboydog** [comment]
Added a setting to this on the default LineView in #25. Thanks for the suggestion
